### GET ALL LOSSES OBJECT
GET http://localhost:8000/api/losses/

### ADD A LOSSE OBJECT
POST http://localhost:8000/api/losses/
Content-Type: application/json

{
     "title": "J'ai rammassé un passport",
    "object_state": "abime(e)",
    "object_description": "Harum atque perspiciatis quaerat quibusdam amet non et adipisci excepturi.",
    "object_image": "https:\/\/via.placeholder.com\/300x300.png\/00ddaa?text=provident",
    "location": "Javierview",
    "date": "2021-12-05",
    "user_id": 2,
    "object_ressource_id": 10
}

### SHOW A SPECIFIC LOSSES OBJECT
GET http://localhost:8000/api/losses/13

### DELETE SPECIFIC LOSSE OBJECT
DELETE http://localhost:8000/api/losses/13

### ================================


### GET ALL FOUNDLOSSES OBJECT
GET http://localhost:8000/api/found-losses/

### DELETE SPECIFIC FOUNDLOSSES OBJECT
DELETE http://localhost:8000/api/found-losses/2

### SHOW A SPECIFIC FOUNDLOSSES OBJECT
GET http://localhost:8000/api/found-losses/14

### ADD NEW FOUNDLOSSES OBJECT
POST http://localhost:8000/api/found-losses/
Content-Type: application/json

{
    "title": "j'ai perdu mon passport",
    "object_state": "neuf(ve)",
    "object_description": "couleur noire",
    "object_image": "https:\/\/via.placeholder.com\/300x300.png\/00eeee?text=cni_cdaoS",
    "location": "dakar",
    "date": "2022-05-15",
    "user_id": 2,
    "object_ressource_id": 9,
    "returned": 0,
    "created_at": "2022-06-13T11:38:58.000000Z",
    "updated_at": "2022-06-13T11:38:58.000000Z"
}

### UPDATE A FOUNDLOSSE OBJECT
PATCH http://localhost:8000/api/found-losses/14
Content-Type: application/json

{
   "title": "Updated j'ai perdu mon visa et mon passport",
    "object_state": "neuf(ve)",
    "object_description": "couvré d'une couche de plastique"
}
